language: go

install:
  - go get github.com/golang/lint/golint
  - go install .

script:
  - esc -o static.go main.go
  - go vet .
  - LINT=$(golint .) && echo $LINT
  - test -z "$LINT"
  - GOFMT=$(gofmt -s -d .) && echo $GOFMT
  - test -z "$GOFMT"
